import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <header className="m-3">
          <h1 className="font-bold text-xl">Tarefinhas</h1>
        </header>
        {children}
        <footer>Nos siga nas redes sociais!</footer>
      </body>
    </html>
  );
}
